on: [push]

jobs:
  run_maven_test:
    runs-on: ubuntu-latest
    name: Run Maven Test
    steps:
      - id: foo
        uses: joshua-williamsOktana/compositeActionTest@main
        with:
          action-repo: 'joshua-williamsOktana/compositeActionTest'
          action-branch: 'main'
      - name: Test Status
        run: echo "${{ steps.foo.outputs.maven-status }}"
        shell: bash
