on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run Maven Test
    steps:
      - id: foo
        uses: joshua-williamsOktana/compositeActionTest@main
      - name: Test Status
        run: echo "The String is ${{ steps.foo.outputs.maven-status }}"
        shell: bash
