on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: joshua-williamsOktana/compositeActionTest@main
      - name: Test Status
        run: echo ${{ steps.foo.outputs.maven-status }}
        shell: bash
